server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xxt?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
  mybatis-plus:
    configuration:
      map-underscore-to-camel-case: true
  thymeleaf:
    check-template-location: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

#自定义的阿里云OSS配置信息
aliyun:
  oss:
    endpoint: 
    accessKeyId:
    accessKeySecret:
    bucketName:

